[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
macros = { path = "../macros" }
colored = { workspace = true }
regex = { workspace = true }